jupyterhub:
    hub:
        services:
            grafana:
                #ENC[AES256_GCM,data:KjgGZ7DicIe5Le2a+/ngw5o2h6YhjDYMvRpZGf8mW7WCGE1xiuwS5wWk3FqVl77HRu50jX3O,iv:TZLhZmxqcxo/dp1sTwrXthU77iGR7dMeBIMMKpnkfdo=,tag:DE66PsmFKPzaoMEo8ZNXAQ==,type:comment]
                #ENC[AES256_GCM,data:5ViGmoEViWwldWd/HEqaV+Hg9zzmQFJ351BnpT3xWPQRw2DZZOsBdOgGvJV287kE5c2a,iv:ZYbMbgcvYkj2VsZPYJSM86vFN+fFoPUqj36pvOHnosg=,tag:gJtZ2NjsS1o9UDWQzV1e3g==,type:comment]
                api_token: ENC[AES256_GCM,data:gp9WapIi6cwurqD6MXDRl7547muWYTzPrniaQi1ahORDiDxIn8sf2tuhZzrkkt/VHAnf/OMkHkFKA4Ajtq4uVw==,iv:AKZrj6TqhXsTO12JutS8pW/cxXRRUaLmZUiWngVF6BY=,tag:mp9MPMFBiDRyrXpW0A89Cw==,type:str]
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:XKII7p7psLZ2WJpuhUOezgzo5wE=,iv:+n1cSMmNVapIO15JllhAysKO/IVAsnrUvip0IYgJij8=,tag:RlPKBGwcQMALenAS4Vlf0A==,type:str]
                client_secret: ENC[AES256_GCM,data:bAs9v3nVnvQ/msi1vgotk+JZFISrkihpYRHNu65EdKYpvLySltBZtg==,iv:IRiyFZHu2mEFc3Y0MbXr3BSAUEhJ0/JE+J9EYybFxsE=,tag:sJfDbp3xhcbOWs9pCZe0Lw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:+1lXW/5zAKuQKa6KriVbN7CkaGS0ZZ4dnjeyrEOANfbrrbZD7A9zOTFRK1iIVYSfqA==,iv:Zdfh0Focn4x0SMrsnnEOPDetriPS5v0iUVXPNwqc9FQ=,tag:WLd50W20+Wfd4GU7tbTwFA==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:wwDCY1cY,iv:FwjSpA0NL+Wy1VHhiAA7hhfi5VtBiWShmpegNk2d31Q=,tag:Lrt1txuNGpT+HYDfoq5mMw==,type:str]
grafana:
    adminUser: ENC[AES256_GCM,data:PjjjlT4=,iv:5xx3VXvaBYuXB/uhSTpzJWcCVANsnwZfhIs0B+/po/4=,tag:tSic6ZvMstFPE2SySb/sfA==,type:str]
    adminPassword: ENC[AES256_GCM,data:5oBCugghr4n0iik2n82aX0U=,iv:4ww3kgIkVhBDAr+wwCsZqnPpJVj8UHiZ3Tz65nmjUCo=,tag:sqHP2MAOcoJS+q0c9IkJqg==,type:str]
    grafana.ini:
        security:
            cookie_secure: ENC[AES256_GCM,data:64w+wg==,iv:qdvWabPcx2nCZ7qLoqrFxmLAOMXOU+UbD+FSgNSOjrw=,tag:2QGydcLPeBoYUhp4bOfVGw==,type:bool]
            secret_key: ENC[AES256_GCM,data:9ZuVBhROKZw7RQUpE8t64SDtzwnZAEzzPNTYXORWCHd5fC1NGnhvBw==,iv:c2SamaDYBdVE7TtAXW7+dOiPsmnHr3TZ2l0iNaeBORE=,tag:wvVtSprKxoWJtbbBr7b8Zw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/neurohackademy/locations/global/keyRings/nh/cryptoKeys/main
          created_at: "2021-06-29T07:49:40Z"
          enc: CiQAbsR6i3ZQRg7ZCFZhjFaKDjweprS03AqebrpnlkEOeDfRxwgSSQANoMcWG5UKOHUhbUbnO/wRUMfEeKTcGuHy6dxSI3tc9ilcLpPHqtvWAaiKH0IVeDCukl/s5EJCAjZoZoKG0AEjOSEP+gWOObw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-30T07:15:11Z"
    mac: ENC[AES256_GCM,data:MmC0m2ih0C6OTCifqgSCycIMlR2ahDX7Rn3erclxTQuevO3wA5LENTrc/4S+j0NgCz3mUbgySa9PbnmKyWc4NvTsasQEtK48MdqktwlvV/HWyy/u0cM4qJvLfjBFZe7+gx/y4VFBWanIo6dkKXIP8osrEp77zkdN0LDSiPUg0KM=,iv:WMYGAokGiVXpfhjZW5dmtxQuTW9BmJ2BVaHDMeZT9UM=,tag:MKMQ7gZDQ2rtM5WioZVZFQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
