jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:XKII7p7psLZ2WJpuhUOezgzo5wE=,iv:+n1cSMmNVapIO15JllhAysKO/IVAsnrUvip0IYgJij8=,tag:RlPKBGwcQMALenAS4Vlf0A==,type:str]
                client_secret: ENC[AES256_GCM,data:bAs9v3nVnvQ/msi1vgotk+JZFISrkihpYRHNu65EdKYpvLySltBZtg==,iv:IRiyFZHu2mEFc3Y0MbXr3BSAUEhJ0/JE+J9EYybFxsE=,tag:sJfDbp3xhcbOWs9pCZe0Lw==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:+1lXW/5zAKuQKa6KriVbN7CkaGS0ZZ4dnjeyrEOANfbrrbZD7A9zOTFRK1iIVYSfqA==,iv:Zdfh0Focn4x0SMrsnnEOPDetriPS5v0iUVXPNwqc9FQ=,tag:WLd50W20+Wfd4GU7tbTwFA==,type:str]
            JupyterHub:
                authenticator_class: ENC[AES256_GCM,data:wwDCY1cY,iv:FwjSpA0NL+Wy1VHhiAA7hhfi5VtBiWShmpegNk2d31Q=,tag:Lrt1txuNGpT+HYDfoq5mMw==,type:str]
grafana:
    adminUser: ENC[AES256_GCM,data:PjjjlT4=,iv:5xx3VXvaBYuXB/uhSTpzJWcCVANsnwZfhIs0B+/po/4=,tag:tSic6ZvMstFPE2SySb/sfA==,type:str]
    adminPassword: ENC[AES256_GCM,data:5oBCugghr4n0iik2n82aX0U=,iv:4ww3kgIkVhBDAr+wwCsZqnPpJVj8UHiZ3Tz65nmjUCo=,tag:sqHP2MAOcoJS+q0c9IkJqg==,type:str]
    grafana.ini:
        security:
            cookie_secure: ENC[AES256_GCM,data:64w+wg==,iv:qdvWabPcx2nCZ7qLoqrFxmLAOMXOU+UbD+FSgNSOjrw=,tag:2QGydcLPeBoYUhp4bOfVGw==,type:bool]
            secret_key: ENC[AES256_GCM,data:9ZuVBhROKZw7RQUpE8t64SDtzwnZAEzzPNTYXORWCHd5fC1NGnhvBw==,iv:c2SamaDYBdVE7TtAXW7+dOiPsmnHr3TZ2l0iNaeBORE=,tag:wvVtSprKxoWJtbbBr7b8Zw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/neurohackademy/locations/global/keyRings/nh/cryptoKeys/main
          created_at: "2021-06-29T07:49:40Z"
          enc: CiQAbsR6i3ZQRg7ZCFZhjFaKDjweprS03AqebrpnlkEOeDfRxwgSSQANoMcWG5UKOHUhbUbnO/wRUMfEeKTcGuHy6dxSI3tc9ilcLpPHqtvWAaiKH0IVeDCukl/s5EJCAjZoZoKG0AEjOSEP+gWOObw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-29T17:27:19Z"
    mac: ENC[AES256_GCM,data:wP13JYJyHkpYkZHTbsf2VrKKIl32hC6JzrDqauIL+icociz6vu4nAzHhsdJ6TGl9PQPyrw5blnAjjqGfnK0uJcKO8I+NwqkFVIync+JYcdxmaVDifV+yN9pVzjCBjHjPPTbavjtA+BXBpTSiUyPA85A32qzlep0J3Q9Obg3WYJE=,iv:Dcct+NHbMcWdoX1TynEdw8Psw34xsv1lnTE+rYKF1Ho=,tag:5zrFDSynAV0bku9IYBeSnQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
