name: deploy-book

# Only run this when the main branch's book folder changes
on:
  push:
    paths:
      - .github/workflows/deploy-book.yaml
      - book/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/deploy-book.yaml
      - book/**
  workflow_dispatch:

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install book dependencies
      run: |
        pip install -r book/requirements.txt

    - name: Build the book
      run: |
        jupyter-book build ./book

    # ref: https://github.com/peaceiris/actions-gh-pages
    - name: Push built book to gh-pages branch
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book/_build/html
        publish_branch: gh-pages
