name: deploy-gke

# Only run this when the main branch's chart/deployments folder changes
on:
  push:
    paths:
      - .github/workflows/deploy-gke.yaml
      - chart/**
      - deployments/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/deploy-gke.yaml
      - chart/**
      - deployments/**
  workflow_dispatch:

# This job:
# - installs gcloud and configures it to use a GCP SA allowed to decrypt
#   encrypted GCR / GKE credentials
# - installs sops and hubploy
# - use hubploy to build an image and deploys the Helm chart to GKE
# - annotates a grafana dashboard that a deployment starts
jobs:
  deploy-gke:
    runs-on: ubuntu-20.04
    environment: prod
    steps:
    - uses: actions/checkout@v2
      with:
        # Required for hubploy's inspection of git history
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # ref: https://github.com/google-github-actions/setup-gcloud
    - uses: google-github-actions/setup-gcloud/@v0.2.1
      with:
        # Secrets configured in https://github.com/neurohackademy/nh2021-jupyterhub/settings/secrets
        # - GCP_SA_KEY is the GCP Service Account .json file in base64:
        #   cat <my-sa.json> | base64 -w0
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        # Required for hubploy's use with SOPS
        export_default_credentials: true

    - name: Install SOPS
      run: |
        curl -sSL https://github.com/mozilla/sops/releases/download/v3.7.1/sops_3.7.1_amd64.deb -o /tmp/sops.deb
        sudo apt-get install /tmp/sops.deb

    - name: Install hubploy
      run: |
        pip install https://github.com/yuvipanda/hubploy/archive/master.zip

    - name: "hubploy: build"
      if: github.event_name != 'push' && github.event_name != 'workflow_dispatch'
      run: |
        hubploy build hub-neurohackademy-org

    - name: "hubploy: build and push"
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        hubploy build hub-neurohackademy-org --push

    ## GitHub Actions doesn't yet provide a simple way to allow-failure of a
    ## step, so this should be commented in when grafana is up and running after
    ## an initial deployment.
    ##
    ## ref: https://github.com/actions/toolkit/issues/399
    ##
    # - name: Create a global Grafana dashboard annotation
    #   uses: frankie567/grafana-annotation-action@v1.0.2
    #   with:
    #     apiHost: https://hub.neurohackademy.org/services/grafana
    #     apiToken: ${{ secrets.GRAFANA_API_TOKEN }}
    #     text: |
    #       Deployment triggered by ${{ github.actor }}.
    #       - <a href="${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}">Inspect CI run</a>
    #       - <a href="${{ github.event.repository.html_url }}/compare/${{ github.event.before }}..${{ github.event.after }}">Compare commits</a>
    #     tags: deployment,github

    - name: "hubploy: deploy"
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        hubploy deploy --namespace default --cleanup-on-fail hub-neurohackademy-org chart prod
